name: Linux

on:
  push:
  pull_request:

jobs:
  ubuntu-24-04:
    runs-on: ubuntu-24.04
    env:
      CC: gcc-13
      CXX: g++-13
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            g++-13 \
            libgtkmm-4.0-dev \
            meson \
            ninja-build \
            pkg-config
      - name: Configure
        run: meson setup build-linux -Dgui=enabled
      - name: Build
        run: meson compile -C build-linux
      - name: Test
        run: meson test -C build-linux --print-errorlogs
